`timescale 1ns/1ps

module instruction_memory_tb;

reg [31:0] address;

wire [31:0] instruction;

instruction_memory uut(

    .address(address),
    .instruction(instruction)

);

initial
begin

    address = 0;

    #10;
    address = 4;

    #10;
    address = 8;

    #10;
    address = 12;

    #10;

    $finish;

end

initial
begin

    $monitor(
      "Time=%0t Address=%d Instruction=%h",
      $time,
      address,
      instruction
    );

end

initial
begin

    $dumpfile("instruction_memory.vcd");
    $dumpvars(0,instruction_memory_tb);
end

endmodule